### ISSUE TITLE
Image flipped in section "eventsection"

### ISSUE THREAD

**Issue by filibert0** [SnowdaysIT/snowdays-front-end#14]
Why the same image flipped upside down as a background for the section id=eventsection?
![image](https://user-images.githubusercontent.com/51334532/73400110-c6994200-42e8-11ea-8b43-147b9e20b032.png)

**Comment by FraTheVet** [comment]
you'll see once #12 is merged :)

**Comment by FraTheVet** [comment]
Closing updates

#24 sends to production #12 with the reversed image being used in the transition effect
