### ISSUE TITLE
Embedded youtube not responsive

### ISSUE THREAD

**Issue by filibert0** [SnowdaysIT/snowdays-front-end#17]
The height of the youtube embedded youtube video-aftermovie is not responsive in height, both on chrome on windows and android. On mobile it's terrible, because it's just a vertical slice, see screenshot 
![image](https://user-images.githubusercontent.com/51334532/73401957-8340d280-42ec-11ea-9f7a-75566a43539b.png)

Other thing: it should have a shadow like all other boxes present in the website!
Last thing: it would be nice to have somewhere in the website the trailer as well. You find it on the youtube channel!

**Comment by FraTheVet** [comment]
Closing updates

Fixed in #12 
#24 sends to production #12 with shadows and responsiveness

**Comment by filibert0** [comment]
Uhm, but any chance you can make it stick to a 16:9 aspect ratio? Now it's more like a 4:3, and the aftermovie is widescreen format :/
