### ISSUE TITLE
Staff gallery

### ISSUE THREAD

**Issue by filibert0** [SnowdaysIT/snowdays-front-end#18]
On chrome on windows, a weird white space is always present below the carousel of images.
![image](https://user-images.githubusercontent.com/51334532/73402091-c7cc6e00-42ec-11ea-8964-542609171265.png)

It would be have the name of the teams show up! Looks like many teams are missing.

**Comment by FraTheVet** [comment]
fixed in #12, closing after merge

**Comment by FraTheVet** [comment]
Closing updates

#24 sends to production #12
